### ISSUE TITLE
[BUG] T life lowers life Expectancy rather than increasing it

### ISSUE THREAD

**Issue by josh11770** [DU-Devs/Dragon-Universe-Public#124]
**Describe the bug**
T Life decreases your decline age and lifespan when injected.

**To Reproduce**
1. buy antivirus
2. Synthesize T-life
3. Inject yourself with mysterious needle
4. See Decreased life stats in med scan

**Expected behavior**
This will slow your decline IMMENSELY. Extending your lifespan nearly 4x its normal amount.

**Screenshots**
![T Life](https://user-images.githubusercontent.com/20744155/124397773-e30c8b80-dcdf-11eb-81b3-1598522f76e5.png)

**Byond Details:**
- Version (ex. 512, 513, etc):
5.0; 514.1557
**First identifiable version:**
What is the earliest version of the game in which you found this bug to exist?
Current as of 7/4/21.

**Comment by Khunkurisu** [comment]
Ironically, there is an issue here but it's not the one you expect.  T-Life lowers your energy slightly, but notably lowers the "rate of power loss from decline" by 4x (notice you went from 4x rate to 1x).  Lifespan is determined by your max ki, that's why it seemed to go down slightly.

The actual issue is the description.  It's misleading because it claims to increase lifespan, when in reality it decreases power loss from old age.

**Comment by Khunkurisu** [comment]
New description is "This will slow your decline IMMENSELY. Decreasing power loss by nearly 4x its normal amount. However, your decline age will be slightly earlier than before."

Issue closed.
