### ISSUE TITLE
[Suggestion] Allow admins to disable auto shadow spar for players

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#154]
**Is your feature request related to a problem? Please describe.**
Yes. Players need to work hard by pressing the arrow keys to gain stats and energy. *How could it be given to then so simply?* 

**Describe the solution you'd like**
Admins should have a toggle for allowing players to use auto shadow spar.

**Describe alternatives you've considered**
Deleting shadow spar from every player, rank and menu.

**Additional context**
N/A.

**Comment by Khunkurisu** [comment]
In the pending update, Shadow Spar is balanced around being much less BP gain, with a focus on energy/mastery.  Shadow Spar is also now on a gain loop like other forms of gains, rather than being each time you attack your shadow.  This makes the idea of manual worthless, on top of being impossible due to the new code.
