### ISSUE TITLE
[Suggestion] Add a 'Target' feature to combat

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#166]
**Is your feature request related to a problem? Please describe.**
While in combat, if more than one players try to attack someone, it is **extremely** likely that they are going to attack each other. I'm making this suggestion to try to add a *possible* better way to do group-based combat.

**Describe the solution you'd like**
Since the game as a Target var for a player, it should be *somewhat* possible to reduce friendly fire of players by adding something like a "attack target only" command for players. My first idea is that it should, like majinize, make players unable to attack non-targeted players and disable homing on non-targeted players.

While this would still make it possible to hit other players with attacks by accident (e.g, they jump in front of it or you use a AOE attack such as self destruct, explosion or final explosion or untargeted attacks like Beams), it would make a HUGE difference in group combat. 

The targeted player should also get untargeted after X amount of minutes without being attacked, and it should also be **manual**, since otherwise I'm pretty sure it would take a large amount of time to get something decent that works without manual player input.

*And since it would make a large difference*, admins being able to toggle it on and off would probably fix that. 

**Describe alternatives you've considered**
Not fighting in groups since a pig teammate is worse than a wolf enemy.

**Additional context**
I don't wanna get hit by a stray charge no more, please. I don't even care if I get kienzan'd in half.

**Comment by Khunkurisu** [comment]
Blasts, lunges, etc should already attempt to home on the player's Target (which is who they're sensing) by default.  That said, in the upcoming update this issue is remedied slightly by the introduction of the party system- which will allow players to fight while on a team without the chance to harm one another, at a cost of damage output.

All that said, I do plan to make it so skills can properly lock-on (with varying degrees of tracking depending on the skill used), but this will take substantially more time and effort than I'm willing to put in until I redo how the skills function overall anyways.
