### ISSUE TITLE
[BUG] Character Duplication(?)

### ISSUE THREAD

**Issue by Beantinn** [DU-Devs/Dragon-Universe-Public#193]
Logged in an alt, caused my main account tab to crash
logged back in and was in a dupe of my char? it was at the as when i logged of my alt. (when I first used the dbs (they were grey/inert, on kaioshin, instantly disappeared and didn't give wish so id guess that's where it started?) 
was able to mind swap back to my "original" body but the old one still remains
Relogging doesn't replicate this, still in the pre-bug body
Game version is 35.8.3
![double](https://user-images.githubusercontent.com/105809177/169096629-05f65a0c-70cd-4790-ab33-06a37296c80c.png)

Edit: it died in one punch, dropped the res i had before too
![Single](https://user-images.githubusercontent.com/105809177/169097125-329254bb-c062-4c54-960d-304ce80187ab.png)

**Comment by Khunkurisu** [comment]
This should only happen in instances where you leave the game suddenly (like a crash) while the game thinks you're in combat.  It's a side effect of an intentional system (prevents your body from vanishing if you log out while fighting), not exactly a bug.  You not logging back into the body when you rejoin though, that's definitely a bug.
