### ISSUE TITLE
[BUG] The Game doesn't load when you open the server

### ISSUE THREAD

**Issue by doldol04** [DU-Devs/Dragon-Universe-Public#196]
The Game doesn't load when you create a server with the DU server manager and then load or create a character. you're just stuck with no map and no data loaded.

1. Start a server with the DU server manager
2. Join through dream daemon
3. make a character or load a character you've made.
4. Nothing loads in.

**Expected behavior**
No map loads in. the tabs on the left say you have 1 bp and just acts like you don't have any progress. none of the UI loads in etc.
it does seem to load in sometimes cause I've had it load twice but outside of that it doesn't load.

This is what I see after loading my character that was made during one of those 2 times the game loaded. same thing happens with making a character.
![image](https://user-images.githubusercontent.com/101526874/174586667-fc8848eb-714b-4684-91c9-51d03843952a.png)

**Byond Details:**
- Version 513 or 514 I forgot which one the latest one was but I updated the game today.

**First identifiable version:**
35.9.1

**Comment by doldol04** [comment]
I just got it to load again and for some reason I'm zoomed out.

**Comment by Khunkurisu** [comment]
This isn't a bug, you're just being impatient.  Each map now only loads when a player tries to enter them for the first time.  So the black screen is simply the game making you wait while the map for that planet loads, and you're spam-reloading before it's done.  The zoomed out problem *is* a bug, but it's one that's caused by spam relogging.

**Comment by doldol04** [comment]
oh ok thanks!
