### ISSUE TITLE
Stats acting strangely 

### ISSUE THREAD

**Issue by Roundstage** [DU-Devs/Dragon-Universe-Public#50]
**Describe the bug**
You can have literaly the minimum amout of stats in the game and if all of your stats are equal you will still having a fully functional build, i was testing it in a private server and every stats scales forever with that so... If you have 0 in everything but speed will you be fast as "Cocaine Addicted Flash", with reflex you will have the ultra instinct and your stats aren't capping on this version. I was testing with the Negative stats and the game just has broken, and when testing with the minimal stats has broken too but my dream daemon wasn't crashed.
That it's pretty annoying, you can be beaten up by a guy who have nothing in stats while having 10k stats.

**To Reproduce**
1. Get a genetics computer.
2. Lower all of your stats to 1
3. See error

**Expected behavior**
Maybe a rework in how this stats are working? Like was in the past when you have a cap system and stats were a floating var like BP, or create a "relative" system like it is in BP... Or just fix that badly game design.

**Screenshots**
https://cdn.discordapp.com/attachments/522214051304964096/726860523299143780/unknown.png
https://cdn.discordapp.com/attachments/522214051304964096/726860587212079114/unknown.png

**Byond Details:**
- 513

**First identifiable version:**
Beta Version.

**Comment by Khunkurisu** [comment]
Stat severity is calculated based on the ratio of it compared to the average of all your stats (stat / [(str + dur + res + spd + for + off + def) / 7]).  I added a modifier based on how close your stats are to the highest stat total in the game.  There is now also a minimum and maximum cap for speed modifiers, so that having excessive speed does not break the game.
