### ISSUE TITLE
[BUG]LSSJ note getting trans

### ISSUE THREAD

**Issue by Farcere** [DU-Devs/Dragon-Universe-Public#60]
**Describe the bug**
LSSJ won't transform with anger, powering up, or from the give ssj verb

**Expected behavior**
A Transforming LSSJ

**Screenshots**
https://giphy.com/gifs/QvqHoMUogmvWAjACDU
**Byond Details:**
- Version 513

**First identifiable version:**
R06/24

**Comment by Khunkurisu** [comment]
This is due to the year requirement.  LSSj can only transform when the in-game year is past the number in their SSJable var.  Not necessarily a bug, but as the year requirement was supposedly removed, it is a bit of an oversight.  On the plus side, the game now starts at year 1 instead of year 0.  Which has simultaneously resolved this issue.
