### ISSUE TITLE
Meditation can clone player and disconnect them[BUG]

### ISSUE THREAD

**Issue by Khunkurisu** [DU-Devs/Dragon-Universe-Public#9]
**Describe the bug**
After sitting and meditating for quite some time, a player can be disconnected and clones of their character might appear.

**To Reproduce**
1. Meditate
2. Leave it for a long while
3. Rejoin after disconnect
4. Admire your progeny

**Expected behavior**
To be neither disconnected nor for there to be clones.

**Screenshots**
N/A

**Byond Details:**
- Version (ex. 512, 513, etc): any

**First identifiable version:**
May 2020 if not earlier.

**Additional context**
N/A

**Comment by Kaseioo** [comment]
This is a bug that has no consistency at all. The only thing that makes it happen, from what I can remember, is meditating. 

It does not seem to need a long meditation time (aka tens of minutes). It just needs for a player to meditate. While I am not sure of this, the bug also seems to be able to happen a few minutes after a player exits meditation as well.

I'm going to list, in order, wha this bugs does.

First, it makes the player game freeze for a few seconds (less than 10).
Then, the player **appears** to be teleported to a void-like area. With that, the player loses ability to use any hotkey and all the Chat Tabs are bugged, getting their verbs removed.

With that, the player can only use the chat-box to use verbs. If they use the OOC verb, their text color will me a random color, not their set color. 

If the player exits the game and enter it again (or relog with F1's Options and Messages), a **new** body will be created for that player. This new body seems to be related to the last time the player logged onto the server. 

For example, if a player logged in at 8am and the bug happened at 8pm, the character would be rolled back (in stats/skills/bp, basically everything) to that point in time.

*However*, since a *new* body is created, the last one still remains on the map. The game seems to treat like a normal player; it can be KOed, killed and everything else that can happen to a player. 

It can even be mindswapped into (this is normally used to fix the rollback problem). 

Also, sometimes that 'old body' (I'm referring to the non-rollbacked one) will repeat an action like Meditating or training and will re-enter it if interruptedy by external means.

**Comment by Khunkurisu** [comment]
This doesn't seem to still be an issue, as far as I can tell.  If this crops up again we can reopen this issue.
