### ISSUE TITLE
[BUG] Fusing ignores previously used skills cooldown from both players

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#95]
**Describe the bug**
If any player uses a skill that has cooldown **or** that was **active** before the fusion and then fuses, the player can use immediately after the fusion. Final Explosion is an example but the most dangerous one is Limit Breaker; a player can use Limit breaker, fuse and then use Limit breaker again.

**To Reproduce**
1. Use a Skill such as Limit breaker.
2. Fuse with someone.
3. Be able to use Limit Breaker once again.

**Expected behavior**
The skills cooldowns should be maintained (by the skills used by Main part of the fusion, probably). Previously active skills should be canceled (limit breaker should stop) or the player should be unable to fuse while that skill is active.

**Screenshots**
N/A.

**Byond Details:**
Any,

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304", but it may also be present since the first fusion update (the beta from 2020.07.06).

**Comment by Khunkurisu** [comment]
Skills with cooldowns being usable by Fused characters is intended- even if they're on cooldown for the people who fused.  However, I have decided for balance-purposes that a few skills can no longer be used by Fused characters.  Limit Breaker is one such skill, so the issue is effectively closed either way!
